# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='focus.Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0'),
        ),
    ]
