# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_keep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='likes',
            new_name='like_num',
        ),
    ]
