# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 10:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0008_auto_20170606_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name=b'\xe6\xad\xa3\xe6\x96\x87'),
        ),
    ]
