# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0010_auto_20170612_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, verbose_name=b'nickname'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name=b'\xe6\xad\xa3\xe6\x96\x87'),
        ),
    ]
