# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0011_auto_20170615_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='profile',
        ),
    ]
